names:
- Battery
- Lighter
- Aerosol
- SupplymentaryBattery
nc: 4
test: C:/Users/kiusw/Desktop/yolov8/test/images
train: C:/Users/kiusw/Desktop/yolov8/train/images
val: C:/Users/kiusw/Desktop/yolov8/valid/images