names:
- Battery
- Lighter
- Aerosol
- SupplymentaryBattery
nc: 4
test: ../yolo_date/DataSet/privatePR/test/images
train: ../yolo_date/DataSet/privatePR/train/images
val: ../yolo_date/DataSet/privatePR/valid/images